import type { Project } from '../types/portfolio';

export const PROJECTS: Project[] = [
  {
    id: 'deepfake-detection',
    title: 'Deepfake Detection Benchmark',
    category: 'AI Systems',
    shortDesc: 'A comparative study of deepfake detection across spatial, frequency, temporal, and transformer-based paradigms.',
    problem: 'Modern deepfake generation methods produce highly realistic media, making reliable and fair detection increasingly difficult.',
    solution: 'An academic benchmarking framework that evaluates four representative detection paradigms under a unified preprocessing pipeline, controlled datasets, and standardized metrics.',
    outcome: 'Demonstrated clear performance differences between paradigms, with transformer-based models achieving the highest accuracy while highlighting trade-offs in temporal and frequency-based approaches.',
    stack: ['Python', 'PyTorch', 'CUDA', 'scikit-learn', 'MTCNN', 'Transformer'],
    image: '/portfolio/DeepfakeDetection.png',
  },  
  {
    id: 'broom-ai',
    title: 'Broom - AI Diet Trainer',
    category: 'AI Systems',
    shortDesc: 'A personalized nutrition agent using computer vision for macro tracking.',
    problem: 'Standard calorie counters can be tedious for users to maintain manually.',
    solution: 'Internal prototype that recognizes food via camera to simplify daily meal logging.',
    outcome: 'Improved user engagement and reduced time spent on manual data entry.',
    stack: ['Python', 'PyTorch', 'React Native', 'FastAPI'],
    image: '/portfolio/Broom.png',
  },
  {
    id: 'skyline-vantage',
    title: 'Skyline Vantage - PropTech OS',
    category: 'Web & Apps',
    shortDesc: 'Asset management tool for regional property development groups.',
    problem: 'Property managers were using fragmented spreadsheets for maintenance and leasing.',
    solution: 'Unified dashboard providing central access to occupancy stats and basic financial reporting.',
    outcome: 'Simplified administrative workflows for the management team.',
    stack: ['React', 'PostgreSQL', 'Node.js', 'AWS'],
    image: '/portfolio/proptech.png',
  },
  {
    id: 'sonatrach-smart-room',
    title: 'Smart Room Management System',
    category: 'Web & Apps',
    shortDesc: 'Pilot system for remote access and room management using smart lock technology.',
    problem: 'Managing physical access for site facilities was manually intensive and lacked real-time oversight.',
    solution: 'Developed a system utilizing ESP32-C6 hardware with BLE/Wi-Fi and RFID functionality integrated into a web dashboard.',
    outcome: 'Centralized access management and improved workflow clarity for facility teams.',
    stack: ['ESP32-C6', 'ESP-IDF', 'Node-RED', 'MariaDB', 'Javascript'],
    image: '/portfolio/Smartroom.png',
  },
  {
    id: 'metro-alger-access',
    title: 'Metro Tripod Access Control',
    category: 'Web & Apps',
    shortDesc: 'Secure communication and monitoring system for transit access gates.',
    problem: 'Need for synchronized, secure data exchange between remote servers and tripod hardware.',
    solution: 'Python-based services facilitating SSH/SFTP data exchange with a custom monitoring web UI.',
    outcome: 'Enabled secure remote gate monitoring and improved data synchronization for operations.',
    stack: ['Python', 'SSH/SFTP', 'Web UI', 'System Design'],
    image: '/portfolio/Metro.png',
  },
  {
    id: 'aero-logistics',
    title: 'AeroFleet - Drone Logistics',
    category: 'AI Systems',
    shortDesc: 'Swarm intelligence prototype for localized industrial drone delivery.',
    problem: 'Exploring efficient path-finding for multiple units in a confined industrial corridor.',
    solution: 'Pilot system using decentralized algorithms to manage unit coordination.',
    outcome: 'Successful demonstration of autonomous coordination in a controlled test environment.',
    stack: ['C++', 'Rust', 'ROS2', 'Reinforcement Learning'],
    image: '/portfolio/Drone.png',
  },
  {
    id: 'luxe-voyage',
    title: 'LuxeVoyage - Private Aviation',
    category: 'Web & Apps',
    shortDesc: 'Booking MVP for a boutique private jet charter startup.',
    problem: 'Niche travel providers often lack integrated instant-booking tools.',
    solution: 'Early-stage MVP that aggregates available charter windows with a clean interface.',
    outcome: 'Enabled the client to launch their digital booking service for a targeted customer base.',
    stack: ['Next.js', 'Go', 'GraphQL', 'Stripe'],
    image: '/portfolio/aviation.png',
  },
  {
    id: 'genome-pulse',
    title: 'Genome Pulse - Bio-informatics',
    category: 'Web & Apps',
    shortDesc: 'Design exploration for DNA sequencing and comparative analysis.',
    problem: 'Visualizing multi-omic datasets can be challenging for small research teams.',
    solution: 'Concept project using a custom WebGL engine to render high-density markers.',
    outcome: 'Validated the feasibility of high-speed browser-based genetic data visualization.',
    stack: ['TypeScript', 'WebGL', 'Rust', 'WebAssembly'],
    image: '/portfolio/Genomic.png',
  },
  {
    id: 'realestate-ar-tours',
    title: 'Horizon AR - Virtual Showings',
    category: 'Design',
    shortDesc: 'Concept for a web-based AR platform for architectural visualization.',
    problem: 'Property developers need better ways to showcase unbuilt residential units.',
    solution: 'Spatial UI prototype allowing users to view floor plans in AR via mobile browsers.',
    outcome: 'Improved stakeholder clarity on layout and spatial design during pre-sales.',
    stack: ['Figma', 'Three.js', 'WebXR', '8th Wall'],
    image: '/portfolio/Ar_visualisiation.png',
  },
  {
    id: 'carbon-swap',
    title: 'CarbonSwap - Exchange Pilot',
    category: 'Web & Apps',
    shortDesc: 'Blockchain-backed marketplace for regional carbon credit offsets.',
    problem: 'Small organizations lack transparent access to verified carbon offset projects.',
    solution: 'Pilot marketplace for credit retirement using a simplified ledger system.',
    outcome: 'Facilitated the verification and offset process for a select group of local partners.',
    stack: ['Solidity', 'React', 'Node.js', 'Sentinel API'],
    image: '/portfolio/blockchain.png',
  },
  {
    id: 'neo-os',
    title: 'Aether OS - Spatial Desktop',
    category: 'Design',
    shortDesc: 'Internal system exploration for next-generation spatial computing interfaces.',
    problem: 'Current 2D interfaces do not translate effectively to spatial depth.',
    solution: 'Design exploration of gaze-based navigation and layered windowing systems.',
    outcome: 'Established a design framework for future spatial interface implementations.',
    stack: ['Unity', 'Figma', 'C#', 'Leap Motion'],
    image: '/portfolio/os.png',
  },
  {
    id: 'medflow-surgical',
    title: 'MedFlow - Surgical Scheduler',
    category: 'AI Systems',
    shortDesc: 'Prototype developed for a private surgical clinic to optimize theater use.',
    problem: 'Manual scheduling often leads to idle theater time and staff fatigue.',
    solution: 'Predictive scheduling model designed to estimate procedure durations.',
    outcome: 'Improved scheduling accuracy and reduced patient waiting times.',
    stack: ['Python', 'Scikit-learn', 'GraphQL', 'Docker'],
    image: '/portfolio/clinical.png',
  },
  {
    id: 'hectare-land-intel',
    title: 'Hectare - Agricultural Data Hub',
    category: 'Web & Apps',
    shortDesc: 'Land valuation tool for a boutique agricultural investment group.',
    problem: 'Difficulty in accessing consolidated soil and climate data for land assessment.',
    solution: 'Integration of satellite imagery and climate history into a single assessment tool.',
    outcome: 'Enabled faster data-driven evaluations for the investment team.',
    stack: ['Next.js', 'Mapbox', 'Python', 'Google Earth Engine'],
    image: '/portfolio/Agri_data.png',
  },
  {
    id: 'urban-flow',
    title: 'UrbanFlow - Traffic Pilot',
    category: 'AI Systems',
    shortDesc: 'Pilot system for signal optimization in a specific neighborhood corridor.',
    problem: 'Local traffic congestion during peak hours was affecting bus route reliability.',
    solution: 'Reinforcement learning model designed to adjust light timing based on live data.',
    outcome: 'Observed smoother traffic flow and more consistent bus arrival times during the test.',
    stack: ['TensorFlow', 'Kubernetes', 'Python', 'Kafka'],
    image: '/portfolio/urban_trafic.png',
  },
  {
    id: 'quantum-identity',
    title: 'Quanta - Brand System',
    category: 'Design',
    shortDesc: 'Visual identity for an early-stage hardware startup.',
    problem: 'Technical products often lack a cohesive and accessible brand presence.',
    solution: 'Created a minimal visual system designed to reflect the precision of the hardware.',
    outcome: "Provided a professional brand foundation for the client's initial launch.",
    stack: ['Processing', 'Adobe Suite', 'Motion Strategy'],
    image: '/portfolio/quanta.png',
  },
  {
    id: 'kinetic-pulse',
    title: 'Pulse - Startup Film',
    category: 'Video & Motion',
    shortDesc: "Motion graphics film for a startup's initial product launch.",
    problem: 'The client needed a professional visual asset for their pitch presentations.',
    solution: 'Internal build combining procedural 3D simulations and custom typography.',
    outcome: "Delivered a high-impact visual that clarified the startup's core message.",
    stack: ['Houdini', 'After Effects', 'Redshift'],
    image: '/portfolio/Pulse.png',
  },
  {
    id: 'biolink-wearable',
    title: 'BioLink Health Pilot',
    category: 'Web & Apps',
    shortDesc: 'Integration hub prototype for consumer wearable devices.',
    problem: 'Users and wellness coaches have health data fragmented across multiple apps.',
    solution: 'A centralized dashboard concept that aggregates data from various wearables.',
    outcome: 'Simplified data review for coaches and improved patient tracking.',
    stack: ['React', 'Node.js', 'AWS HealthLake', 'TypeScript'],
    image: '/portfolio/biolink.png',
  },
  {
    id: 'voyager-deep',
    title: 'Abyss - Exploration Teaser',
    category: 'Video & Motion',
    shortDesc: 'Visual teaser for a deep-sea exploration prototype vessel.',
    problem: 'Communicating the functionality of a submersible in challenging environments.',
    solution: "Atmospheric 3D render focusing on the vessel's lighting and sensor systems.",
    outcome: "Supported the client's internal presentations for project funding.",
    stack: ['Cinema 4D', 'Unreal Engine 5', 'Octane'],
    image: '/portfolio/Abyss.png',
  },
  {
    id: 'vault-secure',
    title: 'Vault - Behavioral Engine',
    category: 'AI Systems',
    shortDesc: 'Functional prototype that detects abnormal patterns in user sessions.',
    problem: 'Automated scripts can sometimes bypass traditional security checks.',
    solution: 'Neural network designed to analyze interaction rhythms and identify non-human behavior.',
    outcome: "Enhanced security layers for the client's web portal.",
    stack: ['Python', 'Golang', 'Scikit-learn', 'TensorFlow'],
    image: '/portfolio/vault.png',
  },
  {
    id: 'neural-scribe',
    title: 'Neural Scribe - Legal Tool',
    category: 'AI Systems',
    shortDesc: 'Internal drafting assistant for a boutique legal practice.',
    problem: 'Attorneys spent significant time on repetitive document drafting tasks.',
    solution: 'LLM implementation designed to generate initial contract drafts based on templates.',
    outcome: 'Reduced time spent on first-draft generation for common legal documents.',
    stack: ['Llama-3', 'LangGraph', 'PostgreSQL', 'Python'],
    image: '/portfolio/Legal.png',
  },
  {
    id: 'vantage-luxury-retail',
    title: 'Aura - E-commerce Prototype',
    category: 'Web & Apps',
    shortDesc: 'Headless commerce implementation for a boutique fashion brand.',
    problem: 'Legacy platform was slow, leading to user drop-off on mobile devices.',
    solution: 'Headless Next.js architecture designed for fast loading and clean navigation.',
    outcome: 'Improved mobile site performance and user experience.',
    stack: ['Next.js', 'Shopify Plus', 'Tailwind', 'Vercel'],
    image: '/portfolio/e-com.png',
  },
  {
    id: 'solar-grid-ai',
    title: 'Solaris - Energy Pilot',
    category: 'AI Systems',
    shortDesc: 'System for monitoring renewable energy inputs for a local micro-grid.',
    problem: 'Balancing supply and demand in small-scale energy grids.',
    solution: 'Machine learning model designed to forecast energy needs and optimize storage.',
    outcome: 'Improved grid stability for the local community during peak use.',
    stack: ['TensorFlow', 'Python', 'Kafka', 'TimescaleDB'],
    image: '/portfolio/solaris.png',
  },
  {
    id: 'abstract-motion',
    title: 'Perception - Motion Study',
    category: 'Video & Motion',
    shortDesc: 'Internal motion graphics study for a digital conference backdrop.',
    problem: 'Client required high-fidelity ambient visuals for an event.',
    solution: 'Generative art systems combined with 3D animation.',
    outcome: 'Provided a professional visual atmosphere for the event attendees.',
    stack: ['Cinema 4D', 'X-Particles', 'Octane Render'],
    image: '/portfolio/perception.png',
  },
  {
    id: 'cognihealth-ai',
    title: 'CogniHealth - Wellness Assistant',
    category: 'AI Systems',
    shortDesc: 'Concept assistant for preliminary wellness triaging in private clinics.',
    problem: 'Clinics needed a more efficient way to handle initial patient screenings.',
    solution: 'AI implementation designed to conduct basic intake and identify priorities.',
    outcome: 'Simplified the intake process for clinic staff.',
    stack: ['Mistral-7B', 'RAG', 'VectorDB', 'FastAPI'],
    image: '/portfolio/wellness_ai.png',
  },
  {
    id: 'skyline-concierge',
    title: 'Elevate - Resident App',
    category: 'Design',
    shortDesc: 'The digital companion for residents of a multi-unit development.',
    problem: 'Residents needed a simpler way to access building services.',
    solution: 'A minimal interface designed for booking shared amenities and guest access.',
    outcome: 'Increased resident use of amenities and streamlined valet requests.',
    stack: ['Figma', 'Prototyping', 'User Research'],
    image: '/portfolio/residant.png',
  },
  {
    id: 'supply-chain-twin',
    title: 'Regional Supply Chain Twin',
    category: 'Web & Apps',
    shortDesc: 'Logistics visualization tool for a regional distributor.',
    problem: 'The client lacked clear visibility into localized supplier delays.',
    solution: 'Interactive map interface designed to track shipments in real-time.',
    outcome: "Improved the client's ability to respond to logistics disruptions.",
    stack: ['Three.js', 'Mapbox', 'Golang', 'Kubernetes'],
    image: '/portfolio/chain_twin.png',
  },
  {
    id: 'titan-industrial-twin',
    title: 'Titan - Machinery Dashboard',
    category: 'Web & Apps',
    shortDesc: 'Telemetry tool for monitoring the status of heavy industrial equipment.',
    problem: 'Unscheduled maintenance was causing delays in equipment availability.',
    solution: 'A telemetry dashboard that visualizes equipment stress and operating hours.',
    outcome: 'Reduced the frequency of unscheduled repairs through better monitoring.',
    stack: ['React', 'C++', 'WebAssembly', 'MQTT'],
    image: '/portfolio/titan.png',
  },
  {
    id: 'game-ux-ui',
    title: 'RPG Game HUD',
    category: 'Design',
    shortDesc: 'Interface system design for a narrative-driven RPG project.',
    problem: 'Complex game mechanics required a clearer and more intuitive HUD.',
    solution: 'Minimalist interface design that adapts to different gameplay contexts.',
    outcome: 'Improved player focus and reduced cognitive load in internal tests.',
    stack: ['Figma', 'Unreal Engine 5', 'Motion Design'],
    image: '/portfolio/rpg.png',
  },
  {
    id: 'pulse-med-diag',
    title: 'Pulse Diagnostic Pilot',
    category: 'Web & Apps',
    shortDesc: 'Remote telemetry app for private surgical consultations.',
    problem: 'Doctors needed a reliable way to view patient data during remote calls.',
    solution: 'Custom WebRTC implementation with synchronized data and video streams.',
    outcome: 'Enabled effective remote collaboration for a series of medical consults.',
    stack: ['React', 'WebRTC', 'Rust', 'WASM'],
    image: '/portfolio/pulse_diagnostic.png',
  },
  {
    id: 'proptech-valuation',
    title: 'Quantum Estate - Valuation Model',
    category: 'AI Systems',
    shortDesc: 'Prototype valuation model for local commercial real estate.',
    problem: 'Traditional appraisals can be slow for rapid market assessments.',
    solution: 'Internal model incorporating local traffic data and market trends.',
    outcome: 'Provided more consistent baseline valuations for the client team.',
    stack: ['XGBoost', 'Python', 'Snowflake', 'Dbt'],
    image: '/portfolio/quantum_estate.png',
  },
  {
    id: 'heritage-museum',
    title: 'Heritage - Archive Concept',
    category: 'Video & Motion',
    shortDesc: 'Interactive archiving concept for a museum collection.',
    problem: 'Finding ways to make stored artifacts accessible to a digital audience.',
    solution: '3D scanning and a web-based gallery for viewing collections remotely.',
    outcome: 'Successfully demonstrated a new way for users to engage with archives.',
    stack: ['Photogrammetry', 'Unreal Engine', 'Three.js'],
    image: '/portfolio/archive.png',
  },
  {
    id: 'sentient-support',
    title: 'Sentient Support Agent',
    category: 'AI Systems',
    shortDesc: 'Internal resolution engine for a software helpdesk.',
    problem: 'Support teams were handling high volumes of repetitive common queries.',
    solution: 'Custom model implementation trained on internal support documentation.',
    outcome: 'Simplified the resolution of basic support tickets.',
    stack: ['GPT-4o', 'LangChain', 'Pinecone', 'Zendesk API'],
    image: '/portfolio/sentient.png',
  },
  {
    id: 'horizon-ev-cluster',
    title: 'Horizon EV Prototype',
    category: 'Design',
    shortDesc: 'Digital cluster design for an electric vehicle manufacturer.',
    problem: 'Driver interfaces can become cluttered with too many secondary metrics.',
    solution: 'Clean, layered design focusing on essential driving data.',
    outcome: 'Provided a functional framework for driver ergonomics evaluation.',
    stack: ['Figma', 'ProtoPie', 'Automotive UX'],
    image: '/portfolio/horizon_ev.png',
  },
  {
    id: 'threat-horizon',
    title: 'Threat Horizon Visual',
    category: 'Video & Motion',
    shortDesc: '3D motion asset for a cybersecurity service presentation.',
    problem: 'Explaining complex vulnerability patterns to non-technical stakeholders.',
    solution: 'Visual metaphor designed to illustrate network security concepts.',
    outcome: 'Improved stakeholder understanding during project walkthroughs.',
    stack: ['Blender', 'After Effects', 'Redshift'],
    image: '/portfolio/threat_horizon.png',
  },
  {
    id: 'apex-athlete-hub',
    title: 'Apex - Performance Pilot',
    category: 'Web & Apps',
    shortDesc: 'Data hub for a professional sports training facility.',
    problem: 'Trainers had difficulty consolidating data from various sensor vests.',
    solution: 'A unified dashboard that identifies basic fatigue and performance metrics.',
    outcome: 'Simplified training adjustments based on consolidated athlete data.',
    stack: ['React', 'D3.js', 'Python', 'AWS IoT'],
    image: '/portfolio/apex.png',
  },
  {
    id: 'fintech-rebrand',
    title: 'Fintech Startup Identity',
    category: 'Design',
    shortDesc: 'Visual identity system for a regional fintech startup.',
    problem: 'The client needed a professional brand that conveyed reliability.',
    solution: 'Minimal visual identity with a focus on clear typography and clean layouts.',
    outcome: "Established a professional brand foundation for the startup's launch.",
    stack: ['Figma', 'Illustrator', 'Motion Strategy'],
    image: '/portfolio/finetech.png',
  },
  {
    id: 'vortex-viz',
    title: 'Vortex - Visualization Tool',
    category: 'Web & Apps',
    shortDesc: 'Data visualization prototype for monitoring network health.',
    problem: 'Identifying patterns in large datasets was a manual and slow process.',
    solution: 'Web-based engine designed to render complex data in a clear visual format.',
    outcome: 'Observed an improvement in the speed of identifying system irregularities.',
    stack: ['WebGL', 'Rust', 'WebAssembly', 'React'],
    image: '/portfolio/vortex.png',
  },
  {
    id: 'cognitive-crm',
    title: 'Cognitive CRM Workflow',
    category: 'AI Systems',
    shortDesc: 'Workflow enhancement layer for a small business sales team.',
    problem: 'Sales teams were spending too much time on lead triaging.',
    solution: 'Simple predictive model designed to highlight leads with higher conversion likelihood.',
    outcome: 'Improved the efficiency of outbound sales efforts.',
    stack: ['Scikit-learn', 'Salesforce API', 'Node.js'],
    image: '/portfolio/crm.png',
  },
  {
    id: 'cyberpunk-kit',
    title: 'Digital UI Framework',
    category: 'Design',
    shortDesc: 'A design system framework for prototyping digital environments.',
    problem: 'The agency needed a cohesive set of assets for rapid UI prototyping.',
    solution: 'Internal library of modular components for complex interface design.',
    outcome: 'Reduced the time required to build high-fidelity interface prototypes.',
    stack: ['Figma', 'React Components', 'CSS'],
    image: '/portfolio/Digital_UI_Framework.png',
  },
  {
    id: '3d-ui-motion',
    title: 'Interface Motion Study',
    category: 'Video & Motion',
    shortDesc: 'Internal study on the application of depth in digital interfaces.',
    problem: 'Exploring how depth and light can improve user orientation in complex apps.',
    solution: 'Series of motion vignettes demonstrating spatial UI interactions.',
    outcome: 'Informed the UI direction for subsequent agency client projects.',
    stack: ['After Effects', 'Blender', 'Lottie'],
    image: '/portfolio/Interface_Motion_Study.png',
  },
  {
    id: 'saas-marketing',
    title: 'Headless Marketing Site',
    category: 'Web & Apps',
    shortDesc: 'Marketing site implementation for a software provider.',
    problem: 'Slow site performance was impacting user engagement and SEO.',
    solution: 'Modern headless architecture built with Next.js and a cloud CMS.',
    outcome: 'Measured a significant improvement in page load times and core web vitals.',
    stack: ['Next.js', 'Sanity', 'Tailwind', 'Vercel'],
    image: '/portfolio/Headless_Marketing_Site.png',
  },
  {
    id: 'product-teaser',
    title: 'Tech Product Teaser',
    category: 'Video & Motion',
    shortDesc: '3D montage for a hardware product demonstration.',
    problem: 'Need for a professional visual asset to showcase a product prototype.',
    solution: 'Short 3D render focusing on the physical design and material finishes.',
    outcome: "Delivered a professional visual for the client's marketing channels.",
    stack: ['After Effects', 'Cinema 4D', 'Redshift'],
    image: '/portfolio/Tech_Product_Teaser.png',
  },
  {
    id: 'industrial-twin-viz',
    title: 'Process Visualization',
    category: 'Video & Motion',
    shortDesc: '3D visualization for a regional automated facility.',
    problem: 'Complex production processes were difficult to explain to potential partners.',
    solution: "Procedural animation illustrating the facility's workflow from start to finish.",
    outcome: 'Improved clarity in stakeholder meetings and project walkthroughs.',
    stack: ['Cinema 4D', 'Unreal Engine 5', 'After Effects'],
    image: '/portfolio/Process_Visualization.png',
  },
  {
    id: 'institutional-crypto',
    title: 'Crypto Dashboard Pilot',
    category: 'Web & Apps',
    shortDesc: 'Trading dashboard for a private investment group.',
    problem: 'Consolidating data from multiple liquidity sources into a single view.',
    solution: 'Unified interface with integrated order tracking and status monitoring.',
    outcome: "Enabled more efficient oversight of the group's transaction activity.",
    stack: ['React', 'Go', 'WebSockets', 'Redis'],
    image: '/portfolio/Crypto_Dashboard_Pilot.png',
  },
  {
    id: 'velocity-gateway',
    title: 'Velocity Payment Layer',
    category: 'Web & Apps',
    shortDesc: "Optimization layer for a merchant's payment processing workflow.",
    problem: 'Legacy systems were adding unnecessary delays to the transaction flow.',
    solution: 'Edge-deployed gateway designed to streamline payment orchestration.',
    outcome: "Reduced transaction processing time for the client's platform.",
    stack: ['Go', 'Redis', 'Terraform', 'Cloudflare Workers'],
    image: '/portfolio/Velocity_Payment_Layer.png',
  },
  {
    id: 'realestate-bidding-hub',
    title: 'Property Bidding Hub',
    category: 'Web & Apps',
    shortDesc: 'Real-time bidding platform for a property auction house.',
    problem: 'The client needed a reliable digital system for remote auctions.',
    solution: 'Synchronized bidding interface with real-time status updates.',
    outcome: "Successful deployment for the client's remote bidding events.",
    stack: ['Next.js', 'PostgreSQL', 'Socket.io', 'Kubernetes'],
    image: '/portfolio/Property_Bidding_Hub.png',
  },
  {
    id: 'vitality-patient-hub',
    title: 'Vitality Monitoring Hub',
    category: 'Web & Apps',
    shortDesc: 'Telemetry tool for patient health data monitoring.',
    problem: 'Coordinating care for patients required more consistent data access.',
    solution: 'Hub designed to aggregate biometric data with automated alerts.',
    outcome: 'Improved response times for clinicians monitoring patient health.',
    stack: ['React', 'Azure IoT', 'Node.js', 'Swift'],
    image: '/portfolio/Vitality_Monitoring_Hub.png',
  },
  {
    id: 'estate-ledger-smart',
    title: 'Estate Ledger - Closing System',
    category: 'Web & Apps',
    shortDesc: 'Document management system for property closing transactions.',
    problem: 'Paper-heavy closing processes were prone to delays and errors.',
    solution: 'Secure document management system with automated status tracking.',
    outcome: 'Reduced the average time required to finalize property transactions.',
    stack: ['Solidity', 'Hardhat', 'React', 'The Graph'],
    image: '/portfolio/Estate_Ledger_-_Closing_System.png',
  },
];
